# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
lane :deploy do
ruby
tests
python
end

desc "Running ruby script"
desc ""
lane :ruby do
  sh("ruby ../buildScripts/fastlaneScript.rb")
end

lane :python do
  sh("python3 ../buildScripts/fastlaneScript.py")
end

  lane :tests do
    run_tests(scheme: "Appcircle")
  end
  
  lane :build do
    build_app(
    	export_method: "development",
    	export_xcargs: "-allowProvisioningUpdates",
    	scheme: "Appcircle")
  end
end
